import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import { GeistSans, GeistMono } from 'geist/font'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} ${GeistMono.variable} bg-stone-950 text-stone-100`}>{children}</body>
    </html>
  )
}
